# 相关配置
server:
  model: debug
  # 服务根路径
  path: candy
  # 端口
  part: :8088
  # banner 配置
  banner:
    # banner 文件的名字
    name: banner.txt
    # 是否加载
    loading: true
# 数据库相关配置
data:
  # 数据类型
  category: mysql
  # 表前缀
  prefix: t_
  # 数据库名称
  database: test
  # 链接
  ip: localhost
  # 端口
  part: 3306
  # 用户名
  username: root
  # 密码
  password: 12345678
  # 打印sql
  sql: true
  # 初始化SQL配置
  init:
    name: init.sql
    status: false
  # 测试数据SQL配置
  test:
    name: test.sql
    status: false
zap:
  level: info
  format: console
  prefix: '[goweb/candy]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true